name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'action.yml'
      - '.github/workflows/build.yml'

jobs:
  build:
    strategy:
      matrix:
        url:
          - "https://armconverter.com/decryptedappstore/us/app/stikdebug/id6744045754"
        path:
          - App.ipa
          - ''
    runs-on: ubuntu-latest
    steps:
      - name: Download IPA
        uses: level3tjg/decryptedappstore-action@main
        with:
          appstore_url: "${{ matrix.url }}"
          cache: false
          path: ${{ matrix.path }}
          token: "${{ secrets.SESSION_TOKEN }}"

      - name: Check IPA was downloaded
        if: matrix.path != '' && hashFiles('App.ipa') == ''
        run: exit 1
